[package]
name = "star9-protocol"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
ciborium = "0.2"
serde.workspace = true
serde_bytes.workspace = true
star9-core = { version = "0.1.0", path = "../star9-core" }
star9-fs = { version = "0.1.0", path = "../star9-fs" }
star9-task = { version = "0.1.0", path = "../star9-task" }
star9-vfs = { version = "0.1.0", path = "../star9-vfs" }

[dev-dependencies]
serde_json.workspace = true
