[package]
name = "star9-web"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys.workspace = true
star9-core = { path = "../star9-core" }
star9-fs = { path = "../star9-fs" }
star9-protocol = { path = "../star9-protocol" }
star9-rc = { path = "../star9-rc" }
star9-runtime = { path = "../star9-runtime" }
star9-shell = { path = "../star9-shell" }
star9-vfs = { path = "../star9-vfs" }

[dev-dependencies]
serde_json.workspace = true
wasm-bindgen-test = "0.3"
